/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controles.CadastroController;
import entidades.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class TelaCadastro extends javax.swing.JFrame {

    TelaPrincipal telaAnterior;
    
    /**
     * Creates new form TelaCadastro
     */
    private TelaCadastro() {
        initComponents();
    }
    
    public TelaCadastro(TelaPrincipal telaAnterior){
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txFieldEspecificacao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txFieldPrecoVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txFieldPrecoCusto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboHabilitar = new javax.swing.JComboBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do Produto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        txFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Especificação Técnica:");

        txFieldEspecificacao.setColumns(20);
        txFieldEspecificacao.setRows(5);
        jScrollPane2.setViewportView(txFieldEspecificacao);

        jLabel3.setText("Preço de Venda:");

        txFieldPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldPrecoVendaActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço de Custo:");

        txFieldPrecoCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldPrecoCustoActionPerformed(evt);
            }
        });

        jLabel5.setText("Habilitar Venda:");

        comboHabilitar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Habilitado", "Desabilitado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txFieldNome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar))
                            .addComponent(txFieldPrecoVenda)
                            .addComponent(jLabel4)
                            .addComponent(txFieldPrecoCusto)
                            .addComponent(jLabel5)
                            .addComponent(comboHabilitar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFieldPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.out.println("Janela fechada");
        this.telaAnterior.setVisible(true);
        this.telaAnterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void txFieldPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldPrecoVendaActionPerformed

    private void txFieldPrecoCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldPrecoCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldPrecoCustoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("Salvando");
        
        // Valores do FORM
        String nome = txFieldNome.getText();
        String especificacao = txFieldEspecificacao.getText();
        String precoVenda = txFieldPrecoVenda.getText();
        String precoCusto = txFieldPrecoCusto.getText();
        int habilitar = comboHabilitar.getSelectedIndex();
        
        // Validação
        // Nome
        if(nome.length() == 0){
            JOptionPane.showMessageDialog(this, "Nome: campo requerido!");
            return;
        }
        // Especificacao
        if(especificacao.length() == 0){
            JOptionPane.showMessageDialog(this, "Especificação: campo requerido!");
            return;
        }
        // Preço de Venda
        if(precoVenda.length() == 0){
            JOptionPane.showMessageDialog(this, "Preço de Venda: campo requerido!");
            return;
        }
        // Preço de Custo
        if(precoCusto.length() == 0){
            JOptionPane.showMessageDialog(this, "Preço de Custo: campo requerido!");
            return;
        }
        // Habilitado (nao precisa)
        
        // Converte
        double pv, pc;
        try {
            pv = Double.parseDouble(precoVenda);
            pc = Double.parseDouble(precoCusto);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Preços precisam ser números válidos");
            return;
        }               
        boolean habilitado = false;        
        if(habilitar > 0){
            habilitado = true;
        }        
        
        Produto p = new Produto(1, nome, especificacao, pc, pv, habilitado);
        
        CadastroController controlador = new CadastroController();
        if(controlador.cadastrarProduto(p))        {
            JOptionPane.showMessageDialog(this,"Cadastrado com sucesso");
        } else {
            JOptionPane.showMessageDialog(this,"Erro ao cadastrar");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboHabilitar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txFieldEspecificacao;
    private javax.swing.JTextField txFieldNome;
    private javax.swing.JTextField txFieldPrecoCusto;
    private javax.swing.JTextField txFieldPrecoVenda;
    // End of variables declaration//GEN-END:variables
}
